### ISSUE TITLE
Problemas de compatibilidad con PS 8.1.x y 8.0.x

### ISSUE THREAD

**Issue by neocol83** [placetopay/prestashop-placetopay#22]
Hola he tenido dos errores al intentar trabajar con el plug-in en las nuevas versiones.

1. Al tratar de instalar el plug-in en prestashop 8.1.x o 8.0.x obtengo errores en el guzzlehttp me da el siguiente error.

Call to undefined method GuzzleHttp\Utils::chooseHandler()

Pienso que podría ser la versión del guzzlehttp pero no tengo mucha información de cómo actualizarlo

2. Cuando voy a finalizar la venta sale error 500 trate de hacerle debug y logré saber que en el archivo redirect.php no está recibiendo la variable $cart y al enviarla null saca este error, pero no he podido saber por que no la Envia

Espero que puedan ayúdeme gracias

**Comment by freddiegar** [comment]
Prestashop 8.0 y 8.1 is supported now in version 4.0.0
